name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        LOCAL_IMAGE_NAME="my-image-name"
        TIMESTAMP_TAG=$(date +%s)
        FULL_LOCAL_TAG="${LOCAL_IMAGE_NAME}:${TIMESTAMP_TAG}"

        echo "Built full local tag: $FULL_LOCAL_TAG"
        echo "Extracted timestamp tag: $TIMESTAMP_TAG"

        echo "FULL_LOCAL_TAG=$FULL_LOCAL_TAG" >> $GITHUB_ENV
        echo "TIMESTAMP_TAG=$TIMESTAMP_TAG" >> $GITHUB_ENV

        docker build . --file Dockerfile --tag $FULL_LOCAL_TAG

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push to GitHub Container Registry
      run: |
        REPOSITORY=${{ github.repository }}
        GHCR_FULL_TAG="ghcr.io/$REPOSITORY:${{ env.TIMESTAMP_TAG }}"
        
        echo "Tagging ${{ env.FULL_LOCAL_TAG }} as $GHCR_FULL_TAG"
        docker tag ${{ env.FULL_LOCAL_TAG }} $GHCR_FULL_TAG
        
        echo "Pushing $GHCR_FULL_TAG to GitHub Container Registry"
        docker push $GHCR_FULL_TAG

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push to Docker Hub
      run: |
        DOCKER_HUB_IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/markdown-to-htmlweb"
        DOCKER_HUB_FULL_TAG="${DOCKER_HUB_IMAGE_NAME}:${{ env.TIMESTAMP_TAG }}"

        echo "Tagging ${{ env.FULL_LOCAL_TAG }} as $DOCKER_HUB_FULL_TAG"
        docker tag ${{ env.FULL_LOCAL_TAG }} $DOCKER_HUB_FULL_TAG

        echo "Pushing $DOCKER_HUB_FULL_TAG to Docker Hub"
        docker push $DOCKER_HUB_FULL_TAG
